[package]
name = "yewdux-middleware"
version = "0.4.0"
edition = "2021"
keywords = ["yew", "state", "redux", "shared", "container"]
categories = ["wasm", "web-programming", "rust-patterns"]
description = "A Redux-like middleware for Yewdux."
repository = "https://github.com/sysgrok/yewdux-middleware"
license = "MIT OR Apache-2.0"
readme = "README.md"
#forced-target = "wasm32-unknown-unknown"

[dependencies]
yewdux = { version = "0.13.0", default-features = false }
yew = { version = "0.23.0", default-features = false }
