[package]
name = "yewdux-macros"
version = "0.11.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Macros for yewdux (embedded in yewdux-middleware)"

[lib]
proc-macro = true

[dependencies]
darling = "0.20"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.36"
quote = "1.0.14"
syn = "2"
